baseURL: "https://ninanikiforova.org/" 
title: Nina Nikiforova
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: nikiforovannina

taxonomies:
    tag: tags 

params:
    description: Hey! I'm a second year PhD Econ student at Bocconi Univerisity. I am interested in topics spanning the literature of political economy and political science, such as authoritarianism, collective actions problems, collective memory and others. Before starting my PhD I earned MA in economics from New Economic School in Moscow and BSc and MSc in Geography from Moscow State Univerisy.
    author: Nina Nikiforova
    googleAnalyticsID: 
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    math: true
    profileMode:
          enabled: true
          title: Nina Nikiforova
          subtitle:  Hey! I'm a second year PhD Econ student at Bocconi Univerisity.I am interested in topics spanning the literature of political economy and political science, such as authoritarianism, collective actions problems, collective memory and others. Before starting my PhD I earned MA in economics from New Economic School in Moscow and BSc and MSc in Geography from Moscow State Univerisy.
          imageUrl: "/IMAGE.jpg"
          imageWidth: 150
          imageHeight: 150
          imageTitle: 
          buttons:
            - name: Papers
              url: /papers/
            - name: Courses
              url: /courses/
            - name: Design
              url: /design/
              
    socialIcons:
        - name: CV
          url: "/cv.pdf"
        - name: Email
          url: "mailto:nina.nikiforova@phd.unibocconi.it"
        - name: Twitter
          url: "https://twitter.com/nikiforovannina"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Nina Nikiforova"
      icon: "/apple-touch-icon.png"
      iconHeight: 18


      markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

